services:
  db:
    image: postgres:16.4
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  db-store:
